export const SET_AUTH_MODAL = "SET_AUTH_MODAL"
export const SET_NICK_MODAL = "SET_NICK_MODAL"
export const SET_SIDEBAR = "SET_SIDEBAR"
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_PLAYER_DATA = "SET_PLAYER_DATA"

export const LIVECASINOGAMES = "LIVECASINOGAMES"
export const CASINOGAMES = "CASINOGAMES"